### ISSUE TITLE
Version 2.0.2016012101 problem

### ISSUE THREAD

**Issue by happysurf** [piroor/newtabfromlocationbar#10]
Version 2.0.2016012101 + Firefox 44rc2 + Location Bar drop down suggestions click= FAIL (nothing happen);
Version 2.0.2016012101 + Firefox 44rc2 + Location Bar drop down most visited site click = FAIL (open in same tab);

Version 1.0.2016011501 + Firefox 44rc2 + Location Bar drop down suggestions click = OK (open a new tab);
Version 1.0.2016011501 + Firefox 44rc2 + Location Bar drop down most visited site click = OK (open a new tab);

Settings: Lv1 and Lv2, the rest is default.
Back to version 1.0.2016011501 for the moment.
Thanks.

**Comment by piroor** [comment]
Confirmed and the commit c90475c6c66d2641f5148c9924536e292b229b5d should fix this.

**Comment by happysurf** [comment]
For me is fixed.
Thanks.
