### ISSUE TITLE
Does not work in Ubuntu 16.04

### ISSUE THREAD

**Issue by darren12345** [piroor/newtabfromlocationbar#12]
Hi, as title. Works OK in Windows 7 but doesn't seem to have any effect in Ubuntu 16.04 (Firefox is up to date). Thanks.

**Comment by piroor** [comment]
This doesn't happen on my Ubuntu 14.04. Hmm...

**Comment by darren12345** [comment]
Actually, something of a false alarm. I noticed it was working if going to a URL but not for search results. I set browser.search.openintab to True in about:config and everything is working as it should be. Thanks.
