### ISSUE TITLE
can't access option page (v3.0.1)

### ISSUE THREAD

**Issue by Geobert** [piroor/newtabfromlocationbar#17]
![image](https://user-images.githubusercontent.com/72570/33213087-ea31c01e-d11d-11e7-8bb8-0f20c8dc49fa.png)

and it's not working (Nightly)

**Comment by piroor** [comment]
Sorry, I forgot to include it to the xpi...

**Comment by piroor** [comment]
I've uploaded 3.0.2, it will be available soon. Thanks!
