### ISSUE TITLE
[BUG] Cannot save settings on Firefox 71+

### ISSUE THREAD

**Issue by lindongbin** [piroor/newtabfromlocationbar#33]
https://imgur.com/aOZaO9G

**Comment by piroor** [comment]
As I wrote at the README https://github.com/piroor/newtabfromlocationbar/blob/master/README.md this addon looks needless and you can migrate to Firefox's preferences. I also migrated, so I don't use and maintain this addon anymore.

If you really want to use and maintain this, I hope to transfer this repository to you. How about that?
