### ISSUE TITLE
Broken as of 39.0

### ISSUE THREAD

**Issue by loverso** [piroor/newtabfromlocationbar#8]
This worked for me in 35.0 and 37.0, but when I updated to 39.0, it stopped working.  I no longer get new tabs.

(this is a duplicate of issue 7, but that was labeled for 39.0 alpha and doesn't seem to have had any attention).

**Comment by loverso** [comment]
I should have looked at the commit history; it looks like you've just fixed this, but not yet made a release.

**Comment by loverso** [comment]
Any update on this?  I've applied the fix to my own install and am using it successfully, so you should be able to make a release from it.

**Comment by phepworth** [comment]
The fix works like a charm. Who has permissions to make a new release? (I edited my xpi directly and installed.)
It was extremely irksome using firefox without this essential add-on working!

**Comment by piroor** [comment]
Now a new version 1.0.2016011501 is available. Could you try it?
https://addons.mozilla.org/firefox/addon/new-tab-from-location-bar/versions/

**Comment by phepworth** [comment]
It works!

________________________________

**Comment by phepworth** [comment]
I tested it, and it's working fine for me now.

(I've been using a version where I manually applied the change for quite some time, now. I tested your build from the link below using different installation.)

Thanks


Paul

________________________________

**Comment by loverso** [comment]
I've also updated from my own manually applied copy to this.  Working great.  Thank you
